# Generated by Django 3.2.7 on 2021-09-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('numero_paginas', models.IntegerField(max_length=50)),
            ],
        ),
    ]
